const colors = [
  { hex: "#000000", name: "black" },
  { hex: "#777777", name: "dark gray" },
  { hex: "#cccccc", name: "light gray" },
  { hex: "#ac193d", name: "maroon" },
  { hex: "#d24726", name: "red" },
  { hex: "#dc4fad", name: "saturated pink" },
  { hex: "#ff8581", name: "pastel pink" },
  { hex: "#fb886e", name: "pastel orangeish" },
  { hex: "#d2b8a3", name: "brown" },
  { hex: "#ffc471", name: "orange" },
  { hex: "#ffcc00", name: "orange " },
  { hex: "#f9ec75", name: "yellow" },
  { hex: "#95ef63", name: "neon green" },
  { hex: "#82ba00", name: "middle green" },
  { hex: "#a8c8e4", name: "periwinkle" },
  { hex: "#3bd5fb", name: "cyan" },
  { hex: "#74e8d3", name: "sea green" },
  { hex: "#5db2ff", name: "middle blue" },
  { hex: "#03b3b2", name: "light turquoise" },
  { hex: "#008299", name: "dark turquoise" },
  { hex: "#0072c6", name: "dark blue" },
  { hex: "#e2a8e4", name: "purple" },
  { name: "berry red", hex: "#b8256f" },
  { name: "light blue", hex: "#96c3eb" },
  { name: "red", hex: "#db4035" },
  { name: "blue", hex: "#4073ff" },
  { name: "orange", hex: "#ff9933" },
  { name: "grape", hex: "#884dff" },
  { name: "yellow", hex: "#fad000" },
  { name: "violet", hex: "#af38eb" },
  { name: "olive green", hex: "#afb83b" },
  { name: "lavender", hex: "#eb96eb" },
  { name: "lime green", hex: "#7ecc49" },
  { name: "magenta", hex: "#e05194" },
  { name: "green", hex: "#299438" },
  { name: "salmon", hex: "#ff8d85" },
  { name: "mint green", hex: "#6accbc" },
  { name: "charcoal", hex: "#808080" },
  { name: "teal", hex: "#158fad" },
  { name: "grey", hex: "#b8b8b8" },
  { name: "skyblue", hex: "#14aaf5" },
  { name: "taupe", hex: "#ccac93" },
];

export default colors;
